// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4GMI7kQVQcslCNNE8oROLgZMlLZA4QEI',
    appId: '1:148985447827:web:8aca2e622c1349d7ab5466',
    messagingSenderId: '148985447827',
    projectId: 'my-uber-taxi',
    authDomain: 'my-uber-taxi.firebaseapp.com',
    storageBucket: 'my-uber-taxi.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKZrukH4kcrrUBxGpizHKMy86YYQR8-7g',
    appId: '1:148985447827:android:a4d55bb6598d8befab5466',
    messagingSenderId: '148985447827',
    projectId: 'my-uber-taxi',
    databaseURL:
        "https://my-uber-taxi-default-rtdb.asia-southeast1.firebasedatabase.app/",
    storageBucket: 'my-uber-taxi.appspot.com',
  );
}
